### ISSUE TITLE
xbrl parsing exception: cash in/on hand

### ISSUE THREAD

**Issue by joshwong-cs** [uktrade/stream-read-xbrl#183]
example: https://find-and-update.company-information.service.gov.uk/company/04799971/filing-history/MzQyMzMwMTU3OGFkaXF6a2N4/document?format=xhtml&download=1

formatting error meant that values for current assets/bank account and current assets/deposits are in the same cell

**Comment by tom-swart** [comment]
PR to fix: https://github.com/uktrade/stream-read-xbrl/pull/184
